"""add apify crawler and page versioning

Revision ID: 1e44343054a0
Revises: 38413c823d1c
Create Date: 2025-11-17 12:46:30.947459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1e44343054a0'
down_revision: Union[str, None] = '38413c823d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension for embedding storage
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table('apify_crawl_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('apify_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apify_actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('apify_compute_units', sa.Float(), nullable=True),
    sa.Column('apify_cost_usd', sa.Float(), nullable=True),
    sa.Column('run_time_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apify_crawl_run_apify_run_id'), 'apify_crawl_run', ['apify_run_id'], unique=False)
    op.create_index(op.f('ix_apify_crawl_run_client_id'), 'apify_crawl_run', ['client_id'], unique=False)
    op.create_index(op.f('ix_apify_crawl_run_id'), 'apify_crawl_run', ['id'], unique=False)
    op.create_index(op.f('ix_apify_crawl_run_status'), 'apify_crawl_run', ['status'], unique=False)
    op.create_table('client_page_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_page_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_run_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publishing_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('h2_count', sa.Integer(), nullable=False),
    sa.Column('h3_count', sa.Integer(), nullable=False),
    sa.Column('h4_count', sa.Integer(), nullable=False),
    sa.Column('h5_count', sa.Integer(), nullable=False),
    sa.Column('h6_count', sa.Integer(), nullable=False),
    sa.Column('h1_list', sa.JSON(), nullable=True),
    sa.Column('webpage_structure', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('markdown_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('page_weight_kb', sa.Float(), nullable=False),
    sa.Column('page_weight_mb', sa.Float(), nullable=False),
    sa.Column('meta_robots', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('meta_viewport', sa.Text(), nullable=True),
    sa.Column('meta_generator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schema_markup', sa.JSON(), nullable=True),
    sa.Column('schema_types', sa.JSON(), nullable=True),
    sa.Column('hreflang', sa.JSON(), nullable=True),
    sa.Column('internal_links', sa.JSON(), nullable=True),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_links', sa.JSON(), nullable=True),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('total_link_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('image_alt_texts', sa.JSON(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('iframe_count', sa.Integer(), nullable=False),
    sa.Column('og_title', sa.Text(), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.Text(), nullable=True),
    sa.Column('og_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('og_url', sa.Text(), nullable=True),
    sa.Column('og_site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('og_locale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_card', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_title', sa.Text(), nullable=True),
    sa.Column('twitter_description', sa.Text(), nullable=True),
    sa.Column('twitter_image', sa.Text(), nullable=True),
    sa.Column('twitter_site', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_creator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fb_app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fb_admins', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('apify_loaded_url', sa.Text(), nullable=True),
    sa.Column('apify_loaded_time', sa.DateTime(), nullable=True),
    sa.Column('apify_referrer_url', sa.Text(), nullable=True),
    sa.Column('apify_crawl_depth', sa.Integer(), nullable=False),
    sa.Column('apify_request_handler_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apify_has_html', sa.Boolean(), nullable=False),
    sa.Column('apify_has_markdown', sa.Boolean(), nullable=False),
    sa.Column('apify_has_screenshot', sa.Boolean(), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('screenshot_file', sa.Text(), nullable=True),
    sa.Column('html_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('charset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favicon', sa.Text(), nullable=True),
    sa.Column('form_count', sa.Integer(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('button_count', sa.Integer(), nullable=False),
    sa.Column('script_count', sa.Integer(), nullable=False),
    sa.Column('style_count', sa.Integer(), nullable=False),
    sa.Column('external_scripts', sa.Integer(), nullable=False),
    sa.Column('external_stylesheets', sa.Integer(), nullable=False),
    sa.Column('similar_to', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # OpenAI Embeddings (pgvector) - Hidden from UI
    sa.Column('embedding_raw_text', Vector(3072), nullable=True),
    sa.Column('embedding_page_title', Vector(3072), nullable=True),
    sa.Column('embedding_slug', Vector(3072), nullable=True),
    sa.ForeignKeyConstraint(['client_page_id'], ['client_page.id'], ),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['apify_crawl_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_page_version_client_page_id'), 'client_page_version', ['client_page_id'], unique=False)
    op.create_index(op.f('ix_client_page_version_crawl_run_id'), 'client_page_version', ['crawl_run_id'], unique=False)
    op.create_index('ix_client_page_version_created', 'client_page_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_page_version_http_status_code'), 'client_page_version', ['http_status_code'], unique=False)
    op.create_index(op.f('ix_client_page_version_id'), 'client_page_version', ['id'], unique=False)
    op.create_index('ix_client_page_version_page_version', 'client_page_version', ['client_page_id', 'version'], unique=False)
    op.create_index(op.f('ix_client_page_version_version'), 'client_page_version', ['version'], unique=False)
    # Drop tables with foreign key dependencies in correct order
    op.drop_index(op.f('ix_chatmessage_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_pagedata_id'), table_name='pagedata')
    op.drop_table('pagedata')
    op.drop_index(op.f('ix_entity_id'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_keyword_id'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_businessfile_id'), table_name='businessfile')
    op.drop_table('businessfile')
    op.drop_table('article')
    # Drop crawljob before project (due to FK dependency)
    op.drop_index(op.f('ix_crawljob_id'), table_name='crawljob')
    op.drop_table('crawljob')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # Drop GIN index before altering column type
    op.drop_index(op.f('ix_client_page_tags_gin'), table_name='client_page', postgresql_using='gin')
    op.alter_column('client_page', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Array of tag strings for categorization and filtering',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_client_page_tags_gin'), 'client_page', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('client_page', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of tag strings for categorization and filtering',
               existing_nullable=True)
    op.create_table('crawljob',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('urls_discovered', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discovery_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('winning_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pages_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pages_crawled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pages_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('crawljob_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crawljob_pkey'))
    )
    op.create_index(op.f('ix_crawljob_id'), 'crawljob', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sitemap_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='project_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('article_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_pkey'))
    )
    op.create_table('businessfile',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('businessfile_project_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('businessfile_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('businessfile_pkey'))
    )
    op.create_index(op.f('ix_businessfile_id'), 'businessfile', ['id'], unique=False)
    op.create_table('page',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_crawl_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_in_sitemap', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('removed_from_sitemap_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='page_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='page_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_table('keyword',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], name=op.f('keyword_added_by_fkey')),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('keyword_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('keyword_pkey'))
    )
    op.create_index(op.f('ix_keyword_id'), 'keyword', ['id'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('salience_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('entity_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_pkey'))
    )
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=False)
    op.create_table('pagedata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('pagedata_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pagedata_pkey'))
    )
    op.create_index(op.f('ix_pagedata_id'), 'pagedata', ['id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('chatmessage_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chatmessage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatmessage_pkey'))
    )
    op.create_index(op.f('ix_chatmessage_id'), 'chatmessage', ['id'], unique=False)
    op.drop_index(op.f('ix_client_page_version_version'), table_name='client_page_version')
    op.drop_index('ix_client_page_version_page_version', table_name='client_page_version')
    op.drop_index(op.f('ix_client_page_version_id'), table_name='client_page_version')
    op.drop_index(op.f('ix_client_page_version_http_status_code'), table_name='client_page_version')
    op.drop_index('ix_client_page_version_created', table_name='client_page_version')
    op.drop_index(op.f('ix_client_page_version_crawl_run_id'), table_name='client_page_version')
    op.drop_index(op.f('ix_client_page_version_client_page_id'), table_name='client_page_version')
    op.drop_table('client_page_version')
    op.drop_index(op.f('ix_apify_crawl_run_status'), table_name='apify_crawl_run')
    op.drop_index(op.f('ix_apify_crawl_run_id'), table_name='apify_crawl_run')
    op.drop_index(op.f('ix_apify_crawl_run_client_id'), table_name='apify_crawl_run')
    op.drop_index(op.f('ix_apify_crawl_run_apify_run_id'), table_name='apify_crawl_run')
    op.drop_table('apify_crawl_run')
    # ### end Alembic commands ###
