"""add phase 4 crawl progress tracking fields to crawl_run

Revision ID: 2c62e60d1a55
Revises: 56cb77f017b2
Create Date: 2025-11-06 04:19:31.136626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c62e60d1a55'
down_revision: Union[str, None] = '56cb77f017b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_run', sa.Column('current_page_url', sa.Text(), nullable=True))
    op.add_column('crawl_run', sa.Column('progress_percentage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('crawl_run', sa.Column('current_status_message', sa.Text(), nullable=True))
    op.add_column('crawl_run', sa.Column('error_log', sa.JSON(), nullable=True))
    op.add_column('crawl_run', sa.Column('performance_metrics', sa.JSON(), nullable=True))
    op.add_column('crawl_run', sa.Column('api_costs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_run', 'api_costs')
    op.drop_column('crawl_run', 'performance_metrics')
    op.drop_column('crawl_run', 'error_log')
    op.drop_column('crawl_run', 'current_status_message')
    op.drop_column('crawl_run', 'progress_percentage')
    op.drop_column('crawl_run', 'current_page_url')
    # ### end Alembic commands ###
