"""add sitemap tracker models and fields

Revision ID: 38413c823d1c
Revises: 7177c5c3d56d
Create Date: 2025-11-16 17:04:18.705558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38413c823d1c'
down_revision: Union[str, None] = '7177c5c3d56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap_tracker_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sitemap_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('current_url_being_checked', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_urls_in_sitemap', sa.Integer(), nullable=False),
    sa.Column('total_urls_checked', sa.Integer(), nullable=False),
    sa.Column('new_urls_count', sa.Integer(), nullable=False),
    sa.Column('removed_urls_count', sa.Integer(), nullable=False),
    sa.Column('status_code_changes_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_urls_count', sa.Integer(), nullable=False),
    sa.Column('status_code_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('previous_run_id', sa.Uuid(), nullable=True),
    sa.Column('comparison_baseline_snapshot', sa.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('average_response_time_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['previous_run_id'], ['sitemap_tracker_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitemap_tracker_run_client_id'), 'sitemap_tracker_run', ['client_id'], unique=False)
    op.create_index(op.f('ix_sitemap_tracker_run_created_at'), 'sitemap_tracker_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_sitemap_tracker_run_id'), 'sitemap_tracker_run', ['id'], unique=False)
    op.create_index(op.f('ix_sitemap_tracker_run_previous_run_id'), 'sitemap_tracker_run', ['previous_run_id'], unique=False)
    op.create_index(op.f('ix_sitemap_tracker_run_started_at'), 'sitemap_tracker_run', ['started_at'], unique=False)
    op.create_index(op.f('ix_sitemap_tracker_run_status'), 'sitemap_tracker_run', ['status'], unique=False)
    op.create_table('sitemap_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('sitemap_tracker_run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'REMOVED', 'STATUS_CHANGED', name='changetype'), nullable=False),
    sa.Column('old_status_code', sa.Integer(), nullable=True),
    sa.Column('new_status_code', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_to_crawler', sa.Boolean(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('importance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['sitemap_tracker_run_id'], ['sitemap_tracker_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitemap_change_change_type'), 'sitemap_change', ['change_type'], unique=False)
    op.create_index('ix_sitemap_change_client_detected', 'sitemap_change', ['client_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_sitemap_change_client_id'), 'sitemap_change', ['client_id'], unique=False)
    op.create_index('ix_sitemap_change_client_type', 'sitemap_change', ['client_id', 'change_type'], unique=False)
    op.create_index(op.f('ix_sitemap_change_detected_at'), 'sitemap_change', ['detected_at'], unique=False)
    op.create_index(op.f('ix_sitemap_change_id'), 'sitemap_change', ['id'], unique=False)
    op.create_index(op.f('ix_sitemap_change_importance'), 'sitemap_change', ['importance'], unique=False)
    op.create_index(op.f('ix_sitemap_change_new_status_code'), 'sitemap_change', ['new_status_code'], unique=False)
    op.create_index(op.f('ix_sitemap_change_old_status_code'), 'sitemap_change', ['old_status_code'], unique=False)
    op.create_index(op.f('ix_sitemap_change_pushed_to_crawler'), 'sitemap_change', ['pushed_to_crawler'], unique=False)
    op.create_index(op.f('ix_sitemap_change_sitemap_tracker_run_id'), 'sitemap_change', ['sitemap_tracker_run_id'], unique=False)
    op.create_index('ix_sitemap_change_status_codes', 'sitemap_change', ['new_status_code', 'old_status_code'], unique=False)
    op.create_index('ix_sitemap_change_unpushed', 'sitemap_change', ['client_id', 'pushed_to_crawler'], unique=False)
    op.create_index(op.f('ix_sitemap_change_url'), 'sitemap_change', ['url'], unique=False)
    # Commented out old table drops - these tables are not being removed
    # op.drop_table('article')
    # op.drop_index(op.f('ix_keyword_id'), table_name='keyword')
    # op.drop_table('keyword')
    # op.drop_index(op.f('ix_pagedata_id'), table_name='pagedata')
    # op.drop_table('pagedata')
    # op.drop_index(op.f('ix_businessfile_id'), table_name='businessfile')
    # op.drop_table('businessfile')
    # op.drop_index(op.f('ix_project_id'), table_name='project')
    # op.drop_table('project')
    # op.drop_index(op.f('ix_crawljob_id'), table_name='crawljob')
    # op.drop_table('crawljob')
    # op.drop_index(op.f('ix_entity_id'), table_name='entity')
    # op.drop_table('entity')
    # op.drop_index(op.f('ix_page_id'), table_name='page')
    # op.drop_table('page')
    # op.drop_index(op.f('ix_chatmessage_id'), table_name='chatmessage')
    # op.drop_table('chatmessage')

    # Add columns to client table with server defaults for existing rows
    op.add_column('client', sa.Column('sitemap_tracking_frequency', sqlmodel.sql.sqltypes.AutoString(), server_default='weekly', nullable=False))
    op.add_column('client', sa.Column('sitemap_tracker_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('client', sa.Column('sitemap_tracker_configured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('client', sa.Column('last_sitemap_tracker_run_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_client_sitemap_tracker_configured'), 'client', ['sitemap_tracker_configured'], unique=False)
    op.create_foreign_key(None, 'client', 'sitemap_tracker_run', ['last_sitemap_tracker_run_id'], ['id'])

    # Create pagesource enum type before using it
    pagesource_enum = sa.Enum('MANUAL', 'SITEMAP_AUTO', name='pagesource')
    pagesource_enum.create(op.get_bind(), checkfirst=True)

    # Add columns to client_page table with server defaults for existing rows
    op.add_column('client_page', sa.Column('source', pagesource_enum, server_default='MANUAL', nullable=False))
    op.add_column('client_page', sa.Column('sent_to_crawler_at', sa.DateTime(), nullable=True))
    op.add_column('client_page', sa.Column('crawl_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('client_page', sa.Column('in_crawler', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('client_page', sa.Column('status_code_history', sa.JSON(), nullable=True))

    # Comment out unrelated tags column changes that cause type incompatibility
    # op.alter_column('client_page', 'tags',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            comment=None,
    #            existing_comment='Array of tag strings for categorization and filtering',
    #            existing_nullable=True)
    # op.drop_index(op.f('ix_client_page_tags_gin'), table_name='client_page', postgresql_using='gin')

    op.create_index(op.f('ix_client_page_crawl_count'), 'client_page', ['crawl_count'], unique=False)
    op.create_index(op.f('ix_client_page_in_crawler'), 'client_page', ['in_crawler'], unique=False)
    op.create_index(op.f('ix_client_page_source'), 'client_page', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_page_source'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_in_crawler'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_crawl_count'), table_name='client_page')
    op.create_index(op.f('ix_client_page_tags_gin'), 'client_page', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('client_page', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of tag strings for categorization and filtering',
               existing_nullable=True)
    op.drop_column('client_page', 'status_code_history')
    op.drop_column('client_page', 'in_crawler')
    op.drop_column('client_page', 'crawl_count')
    op.drop_column('client_page', 'sent_to_crawler_at')
    op.drop_column('client_page', 'source')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_index(op.f('ix_client_sitemap_tracker_configured'), table_name='client')
    op.drop_column('client', 'last_sitemap_tracker_run_id')
    op.drop_column('client', 'sitemap_tracker_configured')
    op.drop_column('client', 'sitemap_tracker_enabled')
    op.drop_column('client', 'sitemap_tracking_frequency')
    op.create_table('chatmessage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('chatmessage_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chatmessage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatmessage_pkey'))
    )
    op.create_index(op.f('ix_chatmessage_id'), 'chatmessage', ['id'], unique=False)
    op.create_table('page',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_crawl_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_in_sitemap', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('removed_from_sitemap_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='page_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='page_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('salience_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('entity_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_pkey'))
    )
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=False)
    op.create_table('crawljob',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('urls_discovered', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discovery_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('winning_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pages_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pages_crawled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pages_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('crawljob_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crawljob_pkey'))
    )
    op.create_index(op.f('ix_crawljob_id'), 'crawljob', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sitemap_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='project_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('businessfile',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('businessfile_project_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('businessfile_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('businessfile_pkey'))
    )
    op.create_index(op.f('ix_businessfile_id'), 'businessfile', ['id'], unique=False)
    op.create_table('pagedata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('pagedata_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pagedata_pkey'))
    )
    op.create_index(op.f('ix_pagedata_id'), 'pagedata', ['id'], unique=False)
    op.create_table('keyword',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], name=op.f('keyword_added_by_fkey')),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('keyword_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('keyword_pkey'))
    )
    op.create_index(op.f('ix_keyword_id'), 'keyword', ['id'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('article_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_pkey'))
    )
    op.drop_index(op.f('ix_sitemap_change_url'), table_name='sitemap_change')
    op.drop_index('ix_sitemap_change_unpushed', table_name='sitemap_change')
    op.drop_index('ix_sitemap_change_status_codes', table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_sitemap_tracker_run_id'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_pushed_to_crawler'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_old_status_code'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_new_status_code'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_importance'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_id'), table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_detected_at'), table_name='sitemap_change')
    op.drop_index('ix_sitemap_change_client_type', table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_client_id'), table_name='sitemap_change')
    op.drop_index('ix_sitemap_change_client_detected', table_name='sitemap_change')
    op.drop_index(op.f('ix_sitemap_change_change_type'), table_name='sitemap_change')
    op.drop_table('sitemap_change')
    op.drop_index(op.f('ix_sitemap_tracker_run_status'), table_name='sitemap_tracker_run')
    op.drop_index(op.f('ix_sitemap_tracker_run_started_at'), table_name='sitemap_tracker_run')
    op.drop_index(op.f('ix_sitemap_tracker_run_previous_run_id'), table_name='sitemap_tracker_run')
    op.drop_index(op.f('ix_sitemap_tracker_run_id'), table_name='sitemap_tracker_run')
    op.drop_index(op.f('ix_sitemap_tracker_run_created_at'), table_name='sitemap_tracker_run')
    op.drop_index(op.f('ix_sitemap_tracker_run_client_id'), table_name='sitemap_tracker_run')
    op.drop_table('sitemap_tracker_run')
    # ### end Alembic commands ###
