"""add phase 3 data table schema with 22 columns

Revision ID: 56cb77f017b2
Revises: 5fc0e93b76c8
Create Date: 2025-11-06 03:32:20.866554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56cb77f017b2'
down_revision: Union[str, None] = '5fc0e93b76c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('successful_pages', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('data_points_extracted', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_run_client_id'), 'crawl_run', ['client_id'], unique=False)
    op.create_index(op.f('ix_crawl_run_id'), 'crawl_run', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_run_status'), 'crawl_run', ['status'], unique=False)
    op.create_table('data_point',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('crawl_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['client_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_point_crawl_run_id'), 'data_point', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_data_point_data_type'), 'data_point', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_point_id'), 'data_point', ['id'], unique=False)
    op.create_index('ix_data_point_page_data_type', 'data_point', ['page_id', 'data_type'], unique=False)
    op.create_index(op.f('ix_data_point_page_id'), 'data_point', ['page_id'], unique=False)
    op.add_column('client_page', sa.Column('page_title', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('meta_title', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('h1', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('canonical_url', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('hreflang', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('meta_robots', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client_page', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('client_page', sa.Column('body_content', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('webpage_structure', sa.JSON(), nullable=True))
    op.add_column('client_page', sa.Column('schema_markup', sa.JSON(), nullable=True))
    op.add_column('client_page', sa.Column('salient_entities', sa.JSON(), nullable=True))
    op.add_column('client_page', sa.Column('internal_links', sa.JSON(), nullable=True))
    op.add_column('client_page', sa.Column('external_links', sa.JSON(), nullable=True))
    op.add_column('client_page', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('client_page', sa.Column('body_content_embedding', sa.Text(), nullable=True))
    op.add_column('client_page', sa.Column('screenshot_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client_page', sa.Column('screenshot_full_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client_page', sa.Column('last_crawled_at', sa.DateTime(), nullable=True))
    op.add_column('client_page', sa.Column('crawl_run_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_client_page_crawl_run_id'), 'client_page', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_client_page_word_count'), 'client_page', ['word_count'], unique=False)
    op.create_foreign_key(None, 'client_page', 'crawl_run', ['crawl_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_page', type_='foreignkey')
    op.drop_index(op.f('ix_client_page_word_count'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_crawl_run_id'), table_name='client_page')
    op.drop_column('client_page', 'crawl_run_id')
    op.drop_column('client_page', 'last_crawled_at')
    op.drop_column('client_page', 'screenshot_full_url')
    op.drop_column('client_page', 'screenshot_url')
    op.drop_column('client_page', 'body_content_embedding')
    op.drop_column('client_page', 'image_count')
    op.drop_column('client_page', 'external_links')
    op.drop_column('client_page', 'internal_links')
    op.drop_column('client_page', 'salient_entities')
    op.drop_column('client_page', 'schema_markup')
    op.drop_column('client_page', 'webpage_structure')
    op.drop_column('client_page', 'body_content')
    op.drop_column('client_page', 'word_count')
    op.drop_column('client_page', 'meta_robots')
    op.drop_column('client_page', 'hreflang')
    op.drop_column('client_page', 'canonical_url')
    op.drop_column('client_page', 'h1')
    op.drop_column('client_page', 'meta_description')
    op.drop_column('client_page', 'meta_title')
    op.drop_column('client_page', 'page_title')
    op.drop_index(op.f('ix_data_point_page_id'), table_name='data_point')
    op.drop_index('ix_data_point_page_data_type', table_name='data_point')
    op.drop_index(op.f('ix_data_point_id'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_data_type'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_crawl_run_id'), table_name='data_point')
    op.drop_table('data_point')
    op.drop_index(op.f('ix_crawl_run_status'), table_name='crawl_run')
    op.drop_index(op.f('ix_crawl_run_id'), table_name='crawl_run')
    op.drop_index(op.f('ix_crawl_run_client_id'), table_name='crawl_run')
    op.drop_table('crawl_run')
    # ### end Alembic commands ###
