"""add client pages and engine setup tables

Revision ID: 5fc0e93b76c8
Revises: 897e9e0a711a
Create Date: 2025-11-05 20:12:35.224228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5fc0e93b76c8'
down_revision: Union[str, None] = '897e9e0a711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_setup_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('setup_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('successful_pages', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('skipped_pages', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_url', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_setup_run_client_id'), 'engine_setup_run', ['client_id'], unique=False)
    op.create_index(op.f('ix_engine_setup_run_id'), 'engine_setup_run', ['id'], unique=False)
    op.create_index(op.f('ix_engine_setup_run_status'), 'engine_setup_run', ['status'], unique=False)
    op.create_table('client_page',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'url', name='unique_client_url')
    )
    op.create_index(op.f('ix_client_page_client_id'), 'client_page', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_page_id'), 'client_page', ['id'], unique=False)
    op.create_index(op.f('ix_client_page_is_failed'), 'client_page', ['is_failed'], unique=False)
    op.create_index(op.f('ix_client_page_status_code'), 'client_page', ['status_code'], unique=False)
    # Add engine_setup_completed with default value for existing rows
    op.add_column('client', sa.Column('engine_setup_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('client', sa.Column('last_setup_run_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_client_engine_setup_completed'), 'client', ['engine_setup_completed'], unique=False)
    op.drop_constraint(op.f('fk_client_project_lead_id'), 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'projectlead', ['project_lead_id'], ['id'])
    op.create_foreign_key(None, 'client', 'engine_setup_run', ['last_setup_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_project_lead_id'), 'client', 'projectlead', ['project_lead_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_client_engine_setup_completed'), table_name='client')
    op.drop_column('client', 'last_setup_run_id')
    op.drop_column('client', 'engine_setup_completed')
    op.drop_index(op.f('ix_client_page_status_code'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_is_failed'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_id'), table_name='client_page')
    op.drop_index(op.f('ix_client_page_client_id'), table_name='client_page')
    op.drop_table('client_page')
    op.drop_index(op.f('ix_engine_setup_run_status'), table_name='engine_setup_run')
    op.drop_index(op.f('ix_engine_setup_run_id'), table_name='engine_setup_run')
    op.drop_index(op.f('ix_engine_setup_run_client_id'), table_name='engine_setup_run')
    op.drop_table('engine_setup_run')
    # ### end Alembic commands ###
