"""add deep researcher models

Revision ID: 7cc07beed57e
Revises: b8a4418329ce
Create Date: 2025-11-02 00:15:46.372918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cc07beed57e'
down_revision: Union[str, None] = 'b8a4418329ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('search_depth', sa.Integer(), nullable=False),
    sa.Column('retrievers', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('report_content', sa.JSON(), nullable=True),
    sa.Column('report_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sources', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_requests_id'), 'research_requests', ['id'], unique=False)
    op.create_index(op.f('ix_research_requests_status'), 'research_requests', ['status'], unique=False)
    op.create_index(op.f('ix_research_requests_user_id'), 'research_requests', ['user_id'], unique=False)
    op.create_table('research_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_request_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_request_id'], ['research_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_chat_messages_id'), 'research_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_research_chat_messages_research_request_id'), 'research_chat_messages', ['research_request_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_request_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retriever', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_request_id'], ['research_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_id'), 'research_sources', ['id'], unique=False)
    op.create_index(op.f('ix_research_sources_research_request_id'), 'research_sources', ['research_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_sources_research_request_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_chat_messages_research_request_id'), table_name='research_chat_messages')
    op.drop_index(op.f('ix_research_chat_messages_id'), table_name='research_chat_messages')
    op.drop_table('research_chat_messages')
    op.drop_index(op.f('ix_research_requests_user_id'), table_name='research_requests')
    op.drop_index(op.f('ix_research_requests_status'), table_name='research_requests')
    op.drop_index(op.f('ix_research_requests_id'), table_name='research_requests')
    op.drop_table('research_requests')
    # ### end Alembic commands ###
