"""add_slug_to_client

Revision ID: 8169f1e99145
Revises: 2c62e60d1a55
Create Date: 2025-11-12 19:49:33.922256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8169f1e99145'
down_revision: Union[str, None] = '2c62e60d1a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_client_slug'), 'client', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_slug'), table_name='client')
    op.drop_column('client', 'slug')
    # ### end Alembic commands ###
