"""add data point definition model

Revision ID: 99898f8234b9
Revises: 2c62e60d1a55
Create Date: 2025-11-10 21:17:37.245962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99898f8234b9'
down_revision: Union[str, None] = '2c62e60d1a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_point_definition',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sa.Enum('ONPAGE', 'TECHNICAL', 'CONTENT', 'LINKS', 'MEDIA', name='datapointcategory'), nullable=False),
    sa.Column('data_type', sa.Enum('STRING', 'JSON', 'INTEGER', 'VECTOR', 'DATETIME', name='datapointdatatype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('crawl4ai_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl4ai_field')
    )
    op.create_index(op.f('ix_data_point_definition_category'), 'data_point_definition', ['category'], unique=False)
    op.create_index('ix_data_point_definition_category_order', 'data_point_definition', ['category', 'display_order'], unique=False)
    op.create_index(op.f('ix_data_point_definition_data_type'), 'data_point_definition', ['data_type'], unique=False)
    op.create_index(op.f('ix_data_point_definition_display_order'), 'data_point_definition', ['display_order'], unique=False)
    op.create_index(op.f('ix_data_point_definition_id'), 'data_point_definition', ['id'], unique=False)
    op.create_index(op.f('ix_data_point_definition_is_active'), 'data_point_definition', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_point_definition_is_active'), table_name='data_point_definition')
    op.drop_index(op.f('ix_data_point_definition_id'), table_name='data_point_definition')
    op.drop_index(op.f('ix_data_point_definition_display_order'), table_name='data_point_definition')
    op.drop_index(op.f('ix_data_point_definition_data_type'), table_name='data_point_definition')
    op.drop_index('ix_data_point_definition_category_order', table_name='data_point_definition')
    op.drop_index(op.f('ix_data_point_definition_category'), table_name='data_point_definition')
    op.drop_table('data_point_definition')
    op.execute('DROP TYPE datapointcategory')
    op.execute('DROP TYPE datapointdatatype')
    # ### end Alembic commands ###
