"""add_page_sitemap_tracking_and_pagedata_versioning

Revision ID: b8a4418329ce
Revises: c7c081b6e475
Create Date: 2025-11-01 22:49:15.436017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8a4418329ce'
down_revision: Union[str, None] = 'c7c081b6e475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to page table - nullable first, then set defaults and make NOT NULL
    op.add_column('page', sa.Column('is_in_sitemap', sa.Boolean(), nullable=True))
    op.execute("UPDATE page SET is_in_sitemap = TRUE WHERE is_in_sitemap IS NULL")
    op.alter_column('page', 'is_in_sitemap', nullable=False)

    op.add_column('page', sa.Column('removed_from_sitemap_at', sa.DateTime(), nullable=True))

    # Add new columns to pagedata table
    op.add_column('pagedata', sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE pagedata SET version = 1 WHERE version IS NULL")
    op.alter_column('pagedata', 'version', nullable=False)

    op.add_column('pagedata', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.execute("UPDATE pagedata SET is_current = TRUE WHERE is_current IS NULL")
    op.alter_column('pagedata', 'is_current', nullable=False)

    op.add_column('pagedata', sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagedata', 'extraction_method')
    op.drop_column('pagedata', 'is_current')
    op.drop_column('pagedata', 'version')
    op.drop_column('page', 'removed_from_sitemap_at')
    op.drop_column('page', 'is_in_sitemap')
    # ### end Alembic commands ###
