"""add_crawl_job_and_update_page_status

Revision ID: c7c081b6e475
Revises: f07807a7d334
Create Date: 2025-11-01 20:50:12.024035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7c081b6e475'
down_revision: Union[str, None] = 'f07807a7d334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawljob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urls_discovered', sa.Integer(), nullable=False),
    sa.Column('discovery_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('winning_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawljob_id'), 'crawljob', ['id'], unique=False)
    op.add_column('page', sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'extraction_method')
    op.drop_index(op.f('ix_crawljob_id'), table_name='crawljob')
    op.drop_table('crawljob')
    # ### end Alembic commands ###
